### ISSUE TITLE
Undefined variable in inc/functions.php

### ISSUE THREAD

**Issue by s0rbus** [craigwatson/dvsa-test-check#1]
I got this error:
Undefined variable: dates in inc/functions.php on line 140
It looks like array_search($date, $dates['seen']) should be array_search($date, $seen) since $seen is the array passed in to parseDates()

**Comment by andrem03** [comment]
I had the same problem, changing the variable to $seen fixed the problem for you?

**Comment by s0rbus** [comment]
Yes, it worked perfectly after that

**Comment by craigwatson** [comment]
Hi,

Really sorry for missing this - for some reason I didn't get any email notifications of opened GitHub issues.

I have fixed the bug now - apologies again :)

Craig
