### ISSUE TITLE
Captcha Present

### ISSUE THREAD

**Issue by corbinspicer68** [craigwatson/dvsa-test-check#2]
Anyone got a good captcha solver that works for DVLA? Keep getting the captcha present messgae

**Comment by craigwatson** [comment]
Hi,

Really sorry for missing this - for some reason I didn't get any email notifications of opened GitHub issues.

Unfortunately solving the captcha is beyond the scope of the script - I didn't actually look into what would be necessary to solve one.

If you find one that works, please feel free to create a PR for the script and add it :)

Cheers,
Craig

**Comment by corbinspicer68** [comment]
I actually did get round to writing a captcha solver using deathbycaptcha's service.. not letting me create a PR though
