### ISSUE TITLE
Feature Request - Reserve Slot

### ISSUE THREAD

**Issue by corbinspicer68** [craigwatson/dvsa-test-check#3]

**Comment by craigwatson** [comment]
Hi,

Again apologies for not getting to review this sooner.

The ability to actually change a slot was never in-scope for this project as you can only change a slot so many times (I think from memory, three?) - the implications for testing the functionality and getting it wrong would be pretty horrible when I was using my own credentials to test!

Hope that helps, I'm more than happy to review a pull request - but my credentials are no longer valid as I passed my practical test in October last year.

Thanks,
Craig
