### ISSUE TITLE
How do I get started with the code?

### ISSUE THREAD

**Issue by verynewtocode** [craigwatson/dvsa-test-check#6]
Hi. I am very new to computer programming. The instruction here is a little hard to understand. 

For the bit says "server with PHP installed", where do I get one? Can I use Jupyter Notebook? And where, and how do I download PHP?

For the bit "The PHP curl module - this is used to make requests to the DVSA website", how do I download the PHP curl module?

For the bit "To get started, all you need to do is copy/rename secrets.sample.php to secrets.php and fill in your data.", do I copy the code into the Jupyter notebook? Or do I have to download the code and execute them? 

Thanks

**Comment by craigwatson** [comment]
Hi, 

Thanks for the questions - unfortunately they're well beyond the scope of this repository.

To get started with PHP, I would recommend checking around for guides - PHP is a server-side language and requires you to install an interpreter/runtime.

Thanks,
Craig
